# Generated by Django 5.2.5 on 2025-08-07 13:48

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('30ml', '30ml'), ('50ml', '50ml'), ('75ml', '75ml'), ('100ml', '100ml'), ('125ml', '125ml'), ('150ml', '150ml'), ('200ml', '200ml')], max_length=10, verbose_name='حجم')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
                ('original_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت اصلی')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='کد محصول')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تنوع محصول',
                'verbose_name_plural': 'تنوع\u200cهای محصول',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='توضیحات کوتاه')),
                ('gender', models.CharField(choices=[('men', 'مردانه'), ('women', 'زنانه'), ('unisex', 'یونیسکس')], max_length=10, verbose_name='جنسیت')),
                ('size', models.CharField(choices=[('30ml', '30ml'), ('50ml', '50ml'), ('75ml', '75ml'), ('100ml', '100ml'), ('125ml', '125ml'), ('150ml', '150ml'), ('200ml', '200ml')], max_length=10, verbose_name='حجم')),
                ('concentration', models.CharField(blank=True, max_length=50, verbose_name='غلظت')),
                ('notes', models.TextField(blank=True, verbose_name='نت\u200cهای عطر')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
                ('original_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت اصلی')),
                ('discount_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='موجود')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='کد محصول')),
                ('main_image', models.ImageField(upload_to='products/main/', verbose_name='تصویر اصلی')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان متا')),
                ('meta_description', models.TextField(blank=True, verbose_name='توضیحات متا')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='کلمات کلیدی متا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_new', models.BooleanField(default=False, verbose_name='جدید')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='پرفروش')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='تعداد فروش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='brands.brand', verbose_name='برند')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین')),
                ('is_primary', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصولات',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'نظر محصول',
                'verbose_name_plural': 'نظرات محصولات',
                'ordering': ['-created_at'],
            },
        ),
    ]
