# Generated by Django 5.2.5 on 2025-08-07 13:48

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/categories/', verbose_name='تصویر')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان متا')),
                ('meta_description', models.TextField(blank=True, verbose_name='توضیحات متا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی بلاگ',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای بلاگ',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='خلاصه')),
                ('content', ckeditor.fields.RichTextField(verbose_name='محتوای')),
                ('featured_image', models.ImageField(upload_to='blog/posts/', verbose_name='تصویر شاخص')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان متا')),
                ('meta_description', models.TextField(blank=True, verbose_name='توضیحات متا')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='کلمات کلیدی متا')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('archived', 'آرشیو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='اجازه نظرات')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='تعداد لایک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'پست بلاگ',
                'verbose_name_plural': 'پست\u200cهای بلاگ',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.blogcomment', verbose_name='پاسخ به')),
            ],
            options={
                'verbose_name': 'نظر بلاگ',
                'verbose_name_plural': 'نظرات بلاگ',
                'ordering': ['-created_at'],
            },
        ),
    ]
